title: Wahab Olagoke Ibrahim
logo: /assets/img/headshot_circle.png
description: >
  MSc Agribusiness Innovation | Climate-Smart Agriculture Advocate |  
  Sustainable Development Practitioner | Speaker & Youth Leader

show_downloads: true
theme: jekyll-theme-minimal
